name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat >>~/.ssh/config <<END
          Host bastion-host
            hostname ${BASTION_HOSTNAME}
            user ${USER_NAME}
            port 22
            IdentityFile ~/.ssh/private_key
            IdentitiesOnly yes
            StrictHostKeyChecking no
          Host webapp
            hostname ${HOSTNAME}
            user ${USER_NAME}
            port 22
            IdentityFile ~/.ssh/private_key
            IdentitiesOnly yes
            ProxyJump bastion-host
            StrictHostKeyChecking no
          END
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          BASTION_HOSTNAME : ${{ secrets.BASTION_HOSTNAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}
        
      - name: Deploy in EC2
        run: |
          ssh webapp '
          
            sudo su
            cd /home/ubuntu/BezpieczSerw-WebApp &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main &&
            docker-compose -f docker-compose.yml up -d --build 
          '
